### ISSUE TITLE
Executable not working after copying .exe file to other location

### ISSUE THREAD

**Issue by kalbhairab** [marcomq/nimview#14]
I made executable in nimview and works fine but when i copy it to other location it says page is not opening but if i copy paste .html file to another location of .exe file it works well.
Do we need to copy .html file to location of executable. If so why the example provided i.e. todo app runs without .html file

**Comment by marcomq** [comment]
Depends.
If you do not inline the html file, you need to copy everything. Nimview doesn't scan for dependencies automatically.
You may use "npm inline" and name the file "inlined.html". If you do so, the file is automatically included in the .exe and you don't need to copy linked ui files.
There is some example on how to use npm inliner in examples/svelte_todo and also in the svelte and vue examples. Check "npm build" command in package.json

I may replace the inliner tool soon, as the current one doesn't receive maintenance anymore.

**Comment by marcomq** [comment]
Just as short summary:
You need to call the html file "dist/inlined.html" so it gets automatically included into the binary in release mode. The file itself als must not contain external dependencies. You can use npm inliner to create an inlined html file that already includes css, images and javascripts as inlined code.

Until now - I haven't been able to include files with nim by just calling a function. It currently only works with static constant filenames. That's why I specified the file to be "dist/inlined". 

I will probably add this somewhere to the documentation.

**Comment by kalbhairab** [comment]
Your library is nice but if you make youtube video tutorial then it will be best for everyone to understand it

**Comment by marcomq** [comment]
Youtube is a good idea - but I'm not a good youtuber :D 
But creating a video is on my TODO list. Currently, I just added some small section to the readme file.
