### ISSUE TITLE
Can't install in Nimble due to reading `VERSION`

### ISSUE THREAD

**Issue by Yardanico** [marcomq/nimview#2]
Right now it's not possible to install the package from Nimble at all:
```
nimble install nimview
Downloading https://github.com/marcomq/nimview using git
       Tip: 1 messages have been suppressed, use --verbose to show them.
     Error: Could not read package info file in /tmp/nimble_5904/githubcom_marcomqnimview/nimview.nimble;
        ...   Reading as ini file failed with: 
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with: 
        ...     io.nim(861)              readFile
        ... Error: unhandled exception: cannot open: VERSION [IOError]
        ... printPkgInfo() failed.
```

The issue is in https://github.com/marcomq/nimview/blob/main/nimview.nimble#L2 - when `nimble` clones the package, the current directory is not the same as the directory where the `VERSION` file is.

**Comment by Yardanico** [comment]
Actually even when doing `nimble install` from the same dir it won't work because Nimble copies the package anyway.

**Comment by marcomq** [comment]
Thx! 
This was due to a recent change. I actually tested "nimble install" locally in the same dir and it worked on my machine. I would need some deeper debugging to find out why it didn't work... and maybe add a test to the CI pipeline...

I just made a simple fix in https://github.com/marcomq/nimview/commit/6ccf4b5010a85e7d55ed2799a529d9f8663688ad and hard-coded the version string again.
