### ISSUE TITLE
Add React Typescript example

### ISSUE THREAD

**Issue by gavr123456789** [marcomq/nimview#33]
I tried it myself, but I came from GTK(but I know some react typescript) and all these technologies like babel and especially rollup using babel are new to me.   
I got 
```
Uncaught ReferenceError: process is not defined
    <anonymous> React
    <anonymous> bundle.js:2458
    <anonymous> bundle.js:31335
```
on app start, and blank screen.

**Comment by marcomq** [comment]
Hey, thx for trying out nimview.
There is a vue example that uses webpack and babel. Maybe you can check this one, as it is probably closer to react than svelte.

Are you using windows or Linux?
When using Windows, I would recommend to try to run the code in IE11 first in httpserver / debug mode. This usually gives additional hints.
I currently have some time. If you share the code, I can help to debug.

**Comment by gavr123456789** [comment]
Here it is https://github.com/gavr123456789/nimview-react-test  
Im using linux arch.

**Comment by marcomq** [comment]
@gavr123456789 
Now I get it - you are compiling your React code and get this error message in your browser.
It seems that React expects to use Node.js or at least have some variables that tell React if this is production code.

![image](https://user-images.githubusercontent.com/62469331/146910562-cff105cb-2654-46b8-a19c-4bc5d76d732d.png)

I don't think that using the svelte example to mix it with react is a good start.
Using the vue sample might be better. Maybe I can add some "hello world" React sample...

**Comment by gavr123456789** [comment]
Yesterday I spent all my free time after work on this attempt, so I'd better wait for the hello world example, also please add typescript

**Comment by marcomq** [comment]
Here is some minimal sample - not using any backend functionality yet. Seems that react has issues with polyfill on windows.
Maybe it works good on linux, where you don't need to use babel. No typescript added yet.
[react.zip](https://github.com/marcomq/nimview/files/7753814/react.zip)
It may take some time until I will add some proper react example. I don't like React much.

**Comment by gavr123456789** [comment]
Got error when trying to start in debug  
```
Required file index not found at /home/gavr/Projects/nimViewTest/src/public/index.html; cannot start UI; the UI folder needs to be relative to the binary [IOError]
```
I set `start("public/index.html")`   
...  
When I trying to run yarn build I got  
```
Creating an optimized production build...
Failed to compile.

src/index.js
  Line 0:  Parsing error: Cannot find module '@react/babel-preset-app'  
...
```

When I tried to install babel-preset-react-app instead of @babel/preset-react nothing changed

**Comment by marcomq** [comment]
> Required file index not found at /home/gavr/Projects/nimViewTest/src/public/index.html

The file doesn't exist at this location. In the .zip file, I used `start("../build/index.html")` 

> When I trying to run yarn build

No issue on my machine when I tried `npm install && npm run build`

**Comment by marcomq** [comment]
So - I just added an example for react:
https://github.com/marcomq/nimview/pull/34

Just merged it.
It doesn't contain typescript. The other examples also just use plain JS, so I wanted to keep the examples consistent. I guess it shouldn't be a big deal to add typescript support as you can just some react sample code.

You just need to modify following:
- to create inline JS code, you may need to install an inliner, for example "npm install tauri-inliner"
- for IE 11 / babel , you need to  `npm install react-app-polyfill` and include it in your index.js with `import 'react-app-polyfill/ie11'`
- add ` "homepage": "./", "proxy": "http://localhost:8000",` to your package.lock to have relative asset directories and port 8000
- `import backend from "nimview"` whenever you want to trigger backend code from js
- create an `.env` file with content `BUILD_PATH=./dist` to compile js to a `dist` folder instead of `build`

**Comment by gavr123456789** [comment]
Nice, thank you.  
Also it is not possible to use node js right?  
For file browser I need some fs watch, and I cant find something for nim as good as chokidar.

**Comment by marcomq** [comment]
I just had a short look at chokidar and I have no idea on how to use it with nimview. You cannot use js or node for back-end code. At least not in an async way.
Maybe you find some way - but I wouldn't know where to start.
